# Generated by Django 5.1.6 on 2025-03-04 05:48

import forecast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityForecaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('path', models.FilePathField(max_length=255, path=forecast.models.trained_models_cache_path)),
            ],
        ),
    ]
