# Generated by Django 5.1.6 on 2025-03-04 05:23

import os

from django.db import migrations

from forecast.models import trained_models_cache_path, CommodityForecaster


def save_trained_model_entries(apps, schema_editor):
    for entry in os.scandir(trained_models_cache_path()):
        if entry.is_dir() or entry.name == ".gitignore":
            continue
        path = entry.path
        market, commodity = entry.name.split("-", maxsplit=1)
        market = market.replace("_", " ")
        commodity = " ".join(commodity.split("_")[:-1])
        CommodityForecaster(
            path=path, market=market, commodity=commodity,
        ).save()


def delete_all_entries(apps, schema_editor):
    CommodityForecaster.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            save_trained_model_entries, reverse_code=delete_all_entries,
        )
    ]
